# Generated by Django 5.2.5 on 2025-08-21 08:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('measurement_name', models.CharField(max_length=100)),
                ('measurement_type', models.CharField(choices=[('i', 'Integer'), ('f', 'Float'), ('s', 'String'), ('b', 'Boolean'), ('d', 'DateTime'), ('j', 'JSON'), ('x', 'XML'), ('y', 'YAML')], max_length=20)),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Timebase Database',
                'verbose_name_plural': 'Timebase Databases',
                'ordering': ['-timestamp'],
            },
        ),
    ]
