# Generated by Django 5.2.5 on 2025-08-21 11:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('measurement_name', models.CharField(max_length=100)),
                ('measurement_type', models.CharField(choices=[('integer', 'Integer'), ('float', 'Float'), ('string', 'String'), ('boolean', 'Boolean'), ('decimal', 'Decimal')], max_length=20)),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Timebase Database',
                'verbose_name_plural': 'Timebase Databases',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='tbdb_hourly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('measurement_name', models.CharField(max_length=100)),
                ('measurement_type', models.CharField(choices=[('integer', 'Integer'), ('float', 'Float'), ('string', 'String'), ('boolean', 'Boolean'), ('decimal', 'Decimal')], max_length=20)),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Timebase Database (Hourly)',
                'verbose_name_plural': 'Timebase Databases (Hourly)',
                'db_table': 'timebase_tbdb_hourly',
                'ordering': ['-timestamp'],
            },
        ),
    ]
