# Generated by Django 5.2.5 on 2025-08-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timebase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbdb',
            name='measurement_type',
            field=models.CharField(choices=[('integer', 'Integer'), ('float', 'Float'), ('string', 'String'), ('boolean', 'Boolean'), ('decimal', 'Decimal')], max_length=20),
        ),
    ]
