# Generated by Django 5.2.5 on 2025-08-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timebase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tbdb',
            table='timebase_tbdb',
        ),
    ]
