# Generated by Django 5.2.5 on 2025-08-21 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timebase', '0002_alter_tbdb_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbdb',
            options={'ordering': ['-rectime'], 'verbose_name': 'Timebase Database', 'verbose_name_plural': 'Timebase Databases'},
        ),
        migrations.AlterModelOptions(
            name='tbdb_hourly',
            options={'ordering': ['-rectime'], 'verbose_name': 'Timebase Database (Hourly)', 'verbose_name_plural': 'Timebase Databases (Hourly)'},
        ),
        migrations.RenameField(
            model_name='tbdb',
            old_name='timestamp',
            new_name='rectime',
        ),
        migrations.RenameField(
            model_name='tbdb_hourly',
            old_name='timestamp',
            new_name='rectime',
        ),
    ]
