# Generated by Django 5.2.5 on 2025-08-21 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timebase', '0003_alter_tbdb_options_alter_tbdb_hourly_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbdb',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Timebase Database', 'verbose_name_plural': 'Timebase Databases'},
        ),
        migrations.AlterModelOptions(
            name='tbdb_hourly',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Timebase Database (Hourly)', 'verbose_name_plural': 'Timebase Databases (Hourly)'},
        ),
        migrations.RenameField(
            model_name='tbdb',
            old_name='rectime',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='tbdb_hourly',
            old_name='rectime',
            new_name='timestamp',
        ),
    ]
